[sso-session customer-a]
sso_start_url = https://d-abcdef0123.awsapps.com/start
sso_region    = us-east-1
sso_registration_scopes = sso:account:access

[profile customer-a-audit]
sso_session    = customer-a
sso_account_id = 444455556666
sso_role_name  = SecurityAudit
region         = us-east-1
